# Generated by Django 3.2.3 on 2021-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
